# Generated by Django 4.2.18 on 2025-03-18 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_match_team_delete_mymodel_match_away_team_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='odds_api_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='MatchOdds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_win_odds', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('away_win_odds', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('draw_odds', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='odds', to='app.match')),
            ],
        ),
    ]
