# Generated by Django 4.2.18 on 2025-03-18 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_leaguetable'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={},
        ),
        migrations.RemoveField(
            model_name='match',
            name='away_score',
        ),
        migrations.RemoveField(
            model_name='match',
            name='competition',
        ),
        migrations.RemoveField(
            model_name='match',
            name='home_score',
        ),
        migrations.RemoveField(
            model_name='match',
            name='matchweek',
        ),
        migrations.RemoveField(
            model_name='match',
            name='odds_api_id',
        ),
        migrations.RemoveField(
            model_name='match',
            name='venue',
        ),
        migrations.RemoveField(
            model_name='matchodds',
            name='away_win_odds',
        ),
        migrations.RemoveField(
            model_name='matchodds',
            name='draw_odds',
        ),
        migrations.RemoveField(
            model_name='matchodds',
            name='home_win_odds',
        ),
        migrations.RemoveField(
            model_name='team',
            name='short_name',
        ),
        migrations.AddField(
            model_name='matchodds',
            name='away_win',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchodds',
            name='draw',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchodds',
            name='home_win',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='team',
            name='logo_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
