# Generated by Django 4.2.18 on 2025-03-18 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_match_options_remove_match_away_score_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['match_date']},
        ),
        migrations.RemoveField(
            model_name='matchodds',
            name='away_win',
        ),
        migrations.RemoveField(
            model_name='matchodds',
            name='draw',
        ),
        migrations.RemoveField(
            model_name='matchodds',
            name='home_win',
        ),
        migrations.AddField(
            model_name='match',
            name='away_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='competition',
            field=models.CharField(default='Premier League', max_length=100),
        ),
        migrations.AddField(
            model_name='match',
            name='home_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='matchweek',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='match',
            name='odds_api_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='venue',
            field=models.CharField(default='TBD', max_length=100),
        ),
        migrations.AddField(
            model_name='matchodds',
            name='away_win_odds',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='matchodds',
            name='draw_odds',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='matchodds',
            name='home_win_odds',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='short_name',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('live', 'Live'), ('finished', 'Finished'), ('cancelled', 'Cancelled'), ('postponed', 'Postponed')], default='scheduled', max_length=20),
        ),
        migrations.AlterField(
            model_name='team',
            name='logo_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
